create table large(
    id varchar(20) primary key,
    first varchar(50),
    second varchar(50),
    third varchar(50),
    fourth varchar(50),
    fifth varchar(50),
    sixth varchar(50),
    seventh varchar(50),
    eighth varchar(50),
    ninth varchar(50),
    tenth varchar(50),
    eleventh varchar(50),
    twelfth varchar(50),
    thirteenth varchar(50),
    fourteenth varchar(50),
    fifteenth varchar(50),
    sixteenth varchar(50),
    seventeenth varchar(50),
    eighteenth varchar(50),
    nineteenth varchar(50),
    twentieth varchar(50)
);